name: Release

on:
  push:
    branches:
      - master
      - release/*
    paths-ignore:
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Bump Version
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install poetry
        poetry version patch
        git tag v$(poetry version | cut -d ' ' -f 2-)
        git commit -am "Bumped version."
        git push
        git push --tags

    - name: Release to PyPi
      run: |
        poetry publish
